### ISSUE TITLE
Is there a way to add optional includes to the motorAutomation1 makefile?

### ISSUE THREAD

**Issue by GarrettSullivan-Aerotech** [epics-motor/motorAutomation1#13] opened 2022-02-21 16:32 UTC
Different versions of the Automation1 C API can have different header files. For example, Automation1 2.0.1 and 2.1 both contain the file Automation1Variables.h, but Automation1 2.0.0 does not. If the motorAutomation1 [Support makefile](https://github.com/epics-motor/motorAutomation1/blob/main/automation1Sup/Makefile) is not updated to include the additional header, a compiler error will occur. This issue is to discuss if there is a way to add optional includes to the motorAutomation1 makefile or even a way to include all files present in the “Include” directory. The alternative would likely require additional manual configuration on the user’s end, which is not ideal.

**Comment by kmpeters** [comment] 2022-02-22 17:32
We have largely avoided these problems in EPICS modules by getting permission from the vendor to include libraries and header files in the module and then only including the libraries & header files from one version of the SDK.  motorAutomation1 is the only motor driver module that uses vendor libraries; it is much more common for areaDetector drivers to use vendor libraries.

@MarkRivers, do any of the areaDetector drivers you're familiar with have conditional includes to handle different versions of the vendor SDKs?

**Comment by MarkRivers** [comment] 2022-02-22 17:41
> @MarkRivers, do any of the areaDetector modules you're familiar with have conditional includes to handle different versions of the vendor SDKs?

No, each release of an areaDetector module uses a specific SDK version.  Users sometimes update locally to a different version of the SDK by replacing the include files and library files, but they do this at their own risk, because the API may have changed in incompatible ways from what the driver expects.

**Comment by kmpeters** [comment] 2022-02-22 17:45
@GarrettSullivan-Aerotech, how frequently will the Automation1 C API change in the future?  Does a controller need to be upgraded to a 2.1-compatible version of the firmware to use EPICS support built against the 2.1 libraries?

**Comment by rakaerotech** [comment] 2022-02-22 19:53
> how frequently will the Automation1 C API change in the future?

Aerotech releases a new version of Automation1 MDK and iSMC every few months (usually three times a year). This includes updates to the C API.

> Does a controller need to be upgraded to a 2.1-compatible version of the firmware to use EPICS support built against the 2.1 libraries?

Yes, the version of the C API and the version of the iSMC (the controller) must match.

This is one of the reasons we don't want to distribute the C API with motorAutomation1, because the user will definitely need to change the C API to match their version of the controller. This is also why we are asking to handle globs/wildcards for the header includes so these can be dynamic based on what version of the C API a user is using.

**Comment by kmpeters** [comment] 2022-02-22 20:43
I pushed a new branch that allows all the header files in the Include dir to be installed:

https://github.com/epics-motor/motorAutomation1/tree/issue13

This is the only change:

https://github.com/epics-motor/motorAutomation1/commit/38b0ec521126f6b58d4b9b9f07c08b0d00e91974

I've tested it with a stand-alone motorAutomation1 build.  I'll test a submodule build next.

**Comment by kmpeters** [comment] 2022-02-22 20:57
> This is one of the reasons we don't want to distribute the C API with motorAutomation1, because the user will definitely need to change the C API to match their version of the controller.

It is very inconvienient to have to install Windows software to obtain newer versions of the Linux C API.  It would be much more convenient if Aerotech customers could download the Linux C API after logging into the Aerotech website, like they already do for the older ensememble software.

**Comment by rakaerotech** [comment] 2022-03-02 18:03
> @GarrettSullivan-Aerotech, I'll let you confirm this solves the build problems for versions >2.0.0

#12 was confirmed fixed via this change so this solves the build problems for versions > 2.0.0.

> it is very inconvienient to have to install Windows software to obtain newer versions of the Linux C API. It would be much more convenient if Aerotech customers could download the Linux C API after logging into the Aerotech website

Understood, thanks for the suggestion @kmpeters. I've put that into our internal request tracker and we'll consider other distribution methods of the Automation1 APIs for the sake of EPICS (and other similar use-cases).

**Closed** 2022-03-02 19:26 UTC
